
export const GET_ALL_DOMAINS = 'GET_ALL_DOMAINS';
export const CREATE_NEW_DOMAIN = 'CREATE_NEW_DOMAIN';


export const LOAD_DOMAINS_SUCCESS = 'LOAD_DOMAINS_SUCCESS';
export const LOAD_DOMAINS_ERROR = 'LOAD_DOMAINS_ERROR';


export const DELETE_DOMAIN_SUCCESS = 'DELETE_DOMAIN_SUCCESS';
export const DELETE_DOMAIN_ERROR = 'DELETE_DOMAIN_ERROR';


export const CREATE_DOMAIN_SUCCESS = 'CREATE_DOMAIN_SUCCESS';
export const CREATE_DOMAIN_ERROR = 'CREATE_DOMAIN_ERROR';


export const UPDATE_DOMAIN_SUCCESS = 'UPDATE_DOMAIN_SUCCESS';
export const UPDATE_DOMAIN_ERROR = 'UPDATE_DOMAIN_ERROR';



export const LOAD_PROJECTS_SUCCESS = 'LOAD_PROJECTS_SUCCESS';
export const LOAD_PROJECTS_ERROR = 'LOAD_PROJECTS_ERROR';


export const LOAD_ROLE_ASSIGNMENTS_SUCCESS = 'LOAD_ROLE_ASSIGNMENTS_SUCCESS';
export const LOAD_ROLE_ASSIGNMENTS_ERROR = 'LOAD_ROLE_ASSIGNMENTS_ERROR';


export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
export const LOAD_USERS_ERROR = 'LOAD_USERS_ERROR';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_ERROR = 'DELETE_USER_ERROR';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';

export const LOAD_SERVERS_SUCCESS = 'LOAD_SERVERS_SUCCESS';
export const LOAD_SERVERS_ERROR = 'LOAD_SERVERS_ERROR';

export const PAUSE_SERVER_SUCCESS = 'PAUSE_SERVER_SUCCESS';
export const PAUSE_SERVER_ERROR = 'PAUSE_SERVER_ERROR';

export const RESUME_SERVER_SUCCESS = 'RESUME_SERVER_SUCCESS';
export const RESUME_SERVER_ERROR = 'RESUME_SERVER_ERROR';

export const LOAD_CONTAINERS_SUCCESS = 'LOAD_CONTAINERS_SUCCESS';
export const LOAD_CONTAINERS_ERROR = 'LOAD_CONTAINERS_ERROR';

export const CONTAINER_READ_ENABLE_SUCCESS = 'CONTAINER_READ_ENABLE_SUCCESS';
export const CONTAINER_READ_ENABLE_ERROR = 'CONTAINER_READ_ENABLE_ERROR';

export const CONTAINER_READ_DISABLE_SUCCESS = 'CONTAINER_READ_DISABLE_SUCCESS';
export const CONTAINER_READ_DISABLE_ERROR = 'CONTAINER_READ_DISABLE_ERROR';

export const GET_ROLE_SERVICES_SUCCESS = 'GET_ROLE_SERVICES_SUCCESS';
export const GET_ROLE_SERVICES_ERROR = 'GET_ROLE_SERVICES_ERROR';

export const UPLOAD_CONTENT_SUCCESS = 'UPLOAD_CONTENT_SUCCESS';
export const UPLOAD_CONTENT_ERROR = 'UPLOAD_CONTENT_ERROR';

export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS';
export const DOWNLOAD_ERROR = 'DOWNLOAD_ERROR';

export const CONTAINER_CONTENT_SUCCESS = 'CONTAINER_CONTENT_SUCCESS';
export const CONTAINER_CONTENT_ERROR = 'CONTAINER_CONTENT_ERROR';

export const DELETE_CONTAINER_CONTENT_SUCCESS = 'DELETE_CONTAINER_CONTENT_SUCCESS';
export const DELETE_CONTAINER_CONTENT_ERROR = 'DELETE_CONTAINER_CONTENT_ERROR';



